### PR TITLE
refactoring + adding swift as remote state backend 

### PR DESCRIPTION
**Pull request by vmindru**
refactoring , adding the possibility to have multiple backends ( e.g. swift, atlas etc. )

### CODE REVIEW

**Comment by vmindru** [comment]
this is not ready, and not ready for review

**Comment by vmindru** [comment]
got a bit blocked by blowed up swift instance, will redeploy and the continue refactoring :)

**Comment by netflash** [comment]
Sounds good.

**Comment by toddmichael** [comment]
This still relevant?  Just making sure.  Cheers.

**Comment by vmindru** [comment]
yep , on a business trip to Brisbane jetlaged and shit , will get finished it soon, if needed we can close it for now and i will reopen.

**Comment by toddmichael** [comment]
Not at all.  Just checking.  Safe travels mate.

**Comment by toddmichael** [comment]
Let's merge or close.  Thanks.

**Comment by vmindru** [comment]
close this for now i will reopen when will have finally time to take of this :( this one is not yet ready

**Pull request closed without merging**
